on:
  push:
    branches:
      - master
jobs:
  free-build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.12'

      - name: Build
        working-directory: cmd/tcp_over_http
        run: go build

      - name: Upload API
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact-2
          path: cmd/tcp_over_http
          retention-days: 1
